-- 사원
-- 사원번호, 이름, 직급, 입사일, 전화번호, 이메일, 급여, 부서번호
CREATE TABLE SUN_EMPLOYEE(
	--사원번호
	EMPNO NUMBER(6) PRIMARY KEY,
	-- 이름
	NAME VARCHAR2(10),
	-- 직급
	JOBTITLE VARCHAR2(10),
	-- 입사일
	HIREDATE DATE,
	-- 전화번호
	PHONENUMBER VARCHAR2(13),
	-- 이메일
	EMAIL VARCHAR2(50),
	-- 급여
	SAL NUMBER(10),
	-- 부서번호
	DEPTNO NUMBER(3)
);

-- 부서
-- 부서 번호, 부서
CREATE TABLE DEPARTMENT(
	DEPTNO NUMBER(3),
	DEPTNAME VARCHAR2(20)
);

INSERT INTO SUN_EMPLOYEE
(EMPNO, NAME, JOBTITLE, HIREDATE, PHONENUMBER, EMAIL, SAL, DEPTNO)
VALUES((SELECT NVL(MAX(EMPNO), 0)+1 FROM SUN_EMPLOYEE), 'DUM', 'IT', '240730', '010-1111-2222', 'dun@gmail.com', 2000, 40);

INSERT INTO EDU.DEPARTMENT
(DEPTNO, DEPTNAME)
VALUES(40, 'TEST4');

